### ISSUE TITLE
Error when compiling with <%=

### ISSUE THREAD

**Issue by dnlmzw** [gruntjs/grunt-contrib-jst#29]
When trying to compile a jst file as simple as this:

`<div><%= this.id %></div>`

I'm getting the following error:

`SyntaxError: Unexpected token =`

No problem compiling it like this:

`<div><% this.id %></div>`

My Gruntfile.coffee task looks like this:

```
jst:
  compile:
    options:
      prettify: true
      templateSettings:
        interpolate: /\{\{(.+?)\}\}/g
      processName: (filename) ->
        return filename.replace('templates/','').replace '.jst', ''
    expand : true
    cwd: 'templates/'
    dest: 'scripts/templates/'
    src: ['**/*.jst']
    ext: '.js'
```

Running on iMac OS X 10.8.4 with:
grunt-cli v0.1.9, grunt v0.4.1, grunt-contrib-jst v0.5.0 & node v0.10.5
